export { default as Control } from './Control'
export { default as Player } from './Player'
export { default as Play } from './Play'
export { default as Prev } from './Prev'
export { default as Next } from './Next'
export { default as Mute } from './Mute'
