export { default as Control } from './Control/Control'
export { default as Player } from './Player'
export { default as Play } from '../Play/Play'
export { default as Prev } from '../Prev/Prev'
export { default as Next } from './Next/Next'
export { default as Mute } from './Mute/Mute'
