import type { NextPage } from 'next'
import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import LoadingScreen from '@/components/LoadingScreen'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Loading | Carlota Sounds</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <LoadingScreen />
      </main>
    </div>
  )
}

export default Home
